["基本"]
"名稱" = "北極熊"
"代號" = "J2"
"房型" = "四人房"
"特別設備" = "溜滑梯"

["簡要"]
"設計概念" = "以北極熊活潑可愛的形象為設計概念，加入溜滑梯元素，打造富有冒險感和趣味性的房型。"
"床型" = "雙人床 x 2"

["詳細"]
"標題" = "✨✨ 將假期升級成一場與動物朋友共享的冒險 ✨✨"
"設計概念1" = """以北極熊活潑可愛的形象為設計概念，我們打造了一個富有冒險感和趣味性的房型，並加入一個溜滑梯。北極熊作為北極圈居民的代表，是一種勇敢且強壯的動物。透過溜滑梯，旅客可以體驗到與北極熊一起玩耍和冒險的樂趣，為房間帶來更多互動和樂趣。
我們使用北極熊作為房間裝飾元素，有壁畫和玩偶，來呈現北極熊的活潑可愛形象。房間有一個安全且有趣的溜滑梯，以增加房型的冒險感和趣味性。激發居住者的想像力和創造力，並且在室內享受冒險遊戲的樂趣。
這樣的房型設計不僅適合兒童，也適合喜歡冒險和趣味的成年人。北極熊的活潑可愛為旅客帶來一份溫馨和愉悅，讓人感受到北極熊那種天真無邪的魅力。"""
"設計概念2" = """
In the land of eternal ice and snow,
Where the chilling winds fiercely blow,
There roams a creature, pure and white,
A symbol of resilience, a majestic sight."""

["價格"]
"定價" = 10800
"假日" = 7100
"旺日" = 6600
"平日" = 5700
