["標題"]
標題1 = "新悅館"
子標題1 = "這裡擁有一個戶外美麗的泳池和庭園，讓您可以在綠樹和花園的包圍下，盡情享受悠閒的渡假時光。"
標題2 = "一個舒適難忘的度假體驗"
子標題2 = "現代主義風格，美觀明亮，在此將充滿性靈的哲思。從客房中一眼望見青綠農田和藍色天空，讓您的視野和心情都得到了充分的舒展。"

["活動"]
"名稱" = "母親節感恩分享活動 - 抽獎免費住一晚"
簡述 = "人生旅程中，陪伴著我們最要的角色莫過於媽媽。在這特別的日子裡，邀請大家一同感念母親的養育之恩，分享抽祝福，願每一位媽媽都永遠快樂 ❤️✨"
