["基本"]
"一般設備" = "Wi-Fi 網路, 大尺寸 LED 電視, 冰箱, 乾溼分離式浴缸, 吹風機, 免治馬桶, 空調冷氣"
"特別設備" = "精緻客房"
"空間與服務" = "免費早餐, 廚房咖啡機, 大坪數沙發客廳, 發燒音響, 原木餐桌與吧枱, 中島大廚房附烤箱, 溫馨閱讀角落, 戶外戲水池, 戶外美觀草坪與綠色植栽"

["簡要"]
"床型" = "雙人床"
"餐點" = "精緻早餐"
"網路" = "免費 Wi-Fi"
"設備" = "LED 電視、吹風機"

["詳細"]
"標題" = "✨✨ 閤家休閒渡假，朋友歡樂聚會的好地方 ✨✨"
"設計概念1" = ""
"設計概念2" = ""

["價格"]
"定價" = 20000
"假日" = 18000
"旺日" = 16000
"平日" = 14000
"平日定義" = "周日至周五"
"假日定義" = "周六、連續假日(包含前一日)以及國定假日"
"旺日定義" = "寒暑假，暑假：每年 7/1 至 8/31"
"定價使用" = "除夕及農曆年節期間"

["規定"]
"入住時間" = "當日下午 3點 後"
"退房時間" = "翌日早上 11點 前"