["基本"]
"名稱" = "獅子"
"代號" = "J1"
"房型" = "四人房"
"特別設備" = "溜滑梯"

["簡要"]
"設計概念" = "以獅子威武的形象為設計概念，加入溜滑梯元素，打造富有挑戰性和動感的房型"
"床型" = "雙人床 x 2"

["詳細"]
"標題" = "✨✨ 體驗大自然的奇妙之旅，與動物朋友們共度難忘時光 ✨✨"
"設計概念1" = """以獅子為設計概念，我們打造了一個富有挑戰性和動感的房型，並將溜滑梯融入其中。這樣的設計將帶來一種獨特的遊樂氛圍，讓小朋友能夠在室內盡情展現活力和勇氣。獅子象徵著力量和領導力，溜滑梯則代表著冒險和童心，這兩者的結合帶來一種活躍和挑戰性的氛圍。
我們也將獅子融入室內裝飾，使用壁畫與造型來展現獅子的威武。同時，房內有一個特製的溜滑梯，使旅客有一個活潑且動感的遊樂設施。不僅能夠激發居住者的想像力和創造力，還能夠有一種獨特的住房體驗。
這房型既適合兒童，也適合喜歡冒險和挑戰的成年人。溜滑梯的加入為房間增添了活力和趣味，使人能夠在室內放鬆身心，感受遊戲的樂趣。獅子的力量和勇氣，能鼓勵居住者面對挑戰，勇往直前，盡情發揮自己的精神和能量在未來的生活之中。"""
"設計概念2" = """
In the heart of the wilderness, where the wild winds blow,
Roams a majestic creature, with a fiery glow.
With a golden mane that flows, like the sun's embrace,
The mighty lion roams, the king of the wild chase."""

["價格"]
"定價" = 10200
"假日" = 6700
"旺日" = 6200
"平日" = 5300
