["基本"]
"名稱" = "浪漫主義"
"代號" = "B1"
"房型" = "天窗雙人房"

["簡要"]
"設計概念" = "浪漫主義強調情感、個人主義和對自然、歷史、民俗等傳統元素的熱愛和憧憬。"

["詳細"]
"標題" = "✨✨ 您將被鮮豔的色彩和獨特的設計所包圍，感受到一種前衛而充滿活力的住宿體驗 ✨✨"
"設計概念1" = """浪漫主義宣言 ~ Romanticism
浪漫主義是19世紀歐洲興起的一種文學和藝術運動，對當時的社會、政治和文化環境產生了深遠的影響。浪漫主義文學強調個人情感和想像力的重要性，體現了對自然、自由、熱情和非凡的追求。
浪漫主義文學的特點之一是對比、誇張和想像的使用。作家們常常使用強烈的對比手法，將不同的元素置於一起，以突出情感和情節的衝突。他們也傾向於誇大描述，以增強作品的戲劇性效果。此外，他們對想像力的運用非常重視，通過獨特而奇特的情節和形象，創造出令人驚嘆和震撼的藝術效果。
浪漫主義文學追求強烈的藝術效果。作家們嘗試創造出非凡和異乎尋常的情節，將讀者帶入神奇和幻想的世界。他們描述了奇異的事件和神秘的景觀，塑造了超凡和孤獨的叛逆形象。這些形象常常被認為是浪漫主義文學的代表，他們通過對社會現實的反叛和對個人情感的強烈表達，表達了對傳統價值觀和社會秩序的質疑。"""
"設計概念2" = """Every day we should hear at least one
little song, read one good poem, see one
exquisite picture, and, if possible, speak
a few sensible words.
_ Johann Wolfgang von Goethe"""

["價格"]
"定價" = 8500
"假日" = 5500
"旺日" = 4900
"平日" = 4300
