["標題"]
"標題1" = "新樂館"
"子標題1" = "充滿了現代化和舒適的設施。房間簡潔明亮，寬敞舒適，讓您與旅伴可以盡情休息和放鬆。"
"標題2" = "在此度過難忘的時光"
"子標題2" = "我們喜歡野趣體驗的家庭設計了各種動物主題客房，有獅子、北極熊、長頸鹿、犀牛、班馬和麋鹿。您可以儘情幻想森林探險的驚喜，與您的孩子一起享受趣味的體驗。"

["活動"]
"名稱" = "母親節感恩分享活動 - 抽獎免費住一晚"
"簡述" = "人生旅程中，陪伴著我們最要的角色莫過於媽媽。在這特別的日子裡，邀請大家一同感念母親的養育之恩，分享抽祝福，願每一位媽媽都永遠快樂 ❤️✨"
