["基本"]
"名稱" = "未來主義"
"代號" = "A2"
"房型" = "雙人房"

["簡要"]
"設計概念" = "義大利詩人馬里內諦於 1909 年發表“未來主義者宣言”，主張藝術家應全力追求速度，歌頌科技與力量。"

["詳細"]
"標題" = "✨✨ 沉浸於簡約而富有藝術感的空間，享受現代生活的美好與舒適 ✨✨"
"設計概念1" = """未來主義宣言 ~ Futurism
未來主義宣言提出了一系列具有革命性思想的觀點。它們主張藝術家應該摒棄傳統、創新無限，追求速度、力量和現代科技所帶來的可能性。未來主義強調對現代工業社會的熱愛，並將機械化和科技視為創作的核心元素。
未來主義宣言強調創新和進步，它們反對過時的藝術形式和觀念，主張藝術應該與現代社會相結合，以反映時代的變革和現代科技的進步。未來主義者追求激情、力量和動感的表現，他們尋求通過藝術創作來打破傳統的限制，追求新的表達方式和感官體驗。
未來主義宣言也提出了一系列具體的藝術觀點。例如，他們主張藝術應該摒棄平面性，追求立體感和動態感。他們推崇現代科技的發展，將汽車、飛機和速度作為藝術創作的靈感來源。他們認為藝術應該是一種全身心的體驗，要能夠引起觀眾的情感共鳴和反思。"""
"設計概念2" = """
The poet must spend himself with ardor,
splendor, and generosity, to swell the
enthusiastic fervor of the primordial
elements.
_Filippo Tommaso Marinett"""

["價格"]
"定價" = 7000
"假日" = 4500
"旺日" = 4000
"平日" = 3600
