["基本"]
"名稱" = "表現主義"
"代號" = "C1"
"房型" = "玻璃屋雙人房"
"特別設備" = "浪漫獨楝"

["簡要"]
"設計概念" = "表現主義強調通過激烈的筆觸、明亮的色彩和扭曲的形式來表達個人主觀感受和情感體驗。"

["詳細"]
"標題" = "✨✨ 清新的色彩和創新的設計，讓您在舒適中享受時尚的住宿體驗 ✨✨"
"設計概念1" = """表現主義宣言 ~ Expressionism
表現主義是20世紀初興起的一種藝術運動，最初起源於德國，後來在整個歐洲得到廣泛的影響。它不僅體現在文學領域，還在視覺藝術、音樂、劇院和電影等領域中產生了深遠的影響。
表現主義文學的特點之一是對主觀世界的關注。表現主義作家關注個人的精神狀態、情感體驗和思想內容，並試圖以獨特而激烈的方式呈現這些內在世界。他們追求對真實性和真理的直觀體驗，並嘗試以直觀的方式描繪人類內心的奇特和深邃。
表現主義文學強調對外在現實的扭曲和變形。作家們不再追求客觀現實的忠實描繪，而是通過夸張、變形、簡化和象徵等手法，將內在世界的情感和思想內容轉化為形式上的表現。他們創造了一種具有強烈情感和戲劇性效果的語言和形象，以揭示人類存在的困惑、焦慮和內心矛盾。"""
"設計概念2" = """Theoretically there is a perfect possibility
of happiness: believing in the
indestructible element in oneself and not
striving towards it.
_ Franz Kafka"""

["價格"]
"定價" = 9000
"假日" = 5800
"旺日" = 5200
"平日" = 4500
