["活動"]
"顯示" = "是"               # 是/否
"開始日期" = 2023-05-01     # 一定要填日期
"結束日期" = 2023-06-30     # 一定要填日期
"名稱" = "✨網美聖地～走進台北後花園宜蘭Aura Villa🌴🌴"
"簡述" = "來趟療癒之旅，放鬆心情愛自己❤️"
"說明" = """
▪即日起至2023/06/30期間限定優惠活動......
▪雙人房平日👉不指定：$3000
▪四人房平日👉不指定：$5000
▪住宿包含：早餐/下午茶 """
