version: '11'
name: Rainbow

services:
  auravilla:
    restart: unless-stopped
    image: mfshiu/aura-villa:6
    ports:
      - "5005:5000"
    networks:
      - nginx_network

  sleepad:
    restart: unless-stopped
    image: mfshiu/sleepad:1
    ports:
      - "5004:5000"
    networks:
      - nginx_network

  gigooweb:
    restart: unless-stopped
    image: mfshiu/gigooweb:6
    ports:
      - "5003:5000"
    networks:
      - nginx_network

  hoursart:
    restart: unless-stopped
    image: mfshiu/hoursart:6
    ports:
      - "5002:5000"
    networks:
      - nginx_network

  vitamin:
    restart: unless-stopped
    image: mfshiu/vitamin:5
    ports:
      - "5001:5000"
    networks:
      - nginx_network

  sygnal:
    restart: unless-stopped
    image: matrixdotorg/sygnal:latest
    ports:
      - "5101:5000"
    volumes:
      - D:/Work/Vesta/sygnal/sygnal.yaml:/sygnal.yaml
    networks:
      - nginx_network

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - nginx_network
      
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot

networks:
  nginx_network:
    driver: bridge
