["基本"]
"名稱" = "超現實主義"
"代號" = "B2"
"房型" = "雙人房"
"特別設備" = "獨立陽台"

["簡要"]
"設計概念" = "超現實主義通過詭異、夢幻、不合邏輯的形式和象徵來表現超越現實世界的想像力和潛意識。"

["詳細"]
"標題" = "✨✨ 每個細節都精心設計，讓您在時尚中找到舒適與寫意的居住體驗 ✨✨"
"設計概念1" = """超現實主義主義宣言 ~ Surrealism
超現實主義宣言是由安德烈·布勒杜（André Breton）於1924年發表的，這一運動對藝術和文學領域產生了深遠的影響。超現實主義追求超越現實世界的界限，進入潛意識和夢境的領域，探索人類內心深處的矛盾和奇幻。
超現實主義的藝術家和作家們對精神分析學說產生了濃厚的興趣，他們採用了弗洛伊德的理論來研究潛意識和夢境的意象。超現實主義作品嘗試通過表現人類的內在世界，探索生與死、愛與恐懼、理性與瘋狂等矛盾的主題。他們藉由無意識的啟示和直覺的引導，創造出超越現實的異境和幻象。
超現實主義藝術家在創作中常常使用奇特和荒誕的圖像和符號，以營造一種詭異和神秘的氛圍。他們描繪出超現實的景象和場景，打破常規的邏輯和規則，將不相干的事物和形象進行融合和組合。這種破壞現實邏輯的手法旨在引起觀眾的驚奇和思考，營造出一種超越常人理解的詩意世界。"""
"設計概念2" = """I believe in the future resolution of these
two states, dream and reality, which are
seemingly so contradictory, into a kind of
absolute reality, a surreality, if one may so
speak. _ André Breton"""

["價格"]
"定價" = 7500
"假日" = 4800
"旺日" = 4300
"平日" = 3800
