["基本"]
"名稱" = "長頸鹿"
"代號" = "T5"
"房型" = "雙人房"
"特別設備" = "吊椅"

["簡要"]
"設計概念" = "想像在青翠的非洲草原中，躺在舒適的吊椅上，看著長頸鹿優雅地伸展著脖子，享用著枝頭的嫩葉。"

["詳細"]
"標題" = "✨✨ 住在我們的動物主題房中，打造別具一格的假期，讓您的旅程更加豐富多彩 ✨✨"
"設計概念1" = """在遼闊的非洲草原上，幻想著身處於一張舒適的吊椅上，享受陽光灑在身上的溫暖。我們靜靜地坐著，眺望著遠處的景色，眼前突然出現了一隻優雅的長頸鹿。它緩慢地移動著，優雅地伸展著長長的脖子，穩定地撥動著枝頭的嫩葉，享用著大自然的恩賜。
長頸鹿帶來的寧靜與和諧，它的存在使這片草原更加生機勃勃。我們不禁陶醉於它優雅的動作和舒適的環境中，仿佛時光也因此停滯。在這個瞬間，我們與自然融為一體，感受到大自然的美妙之處。
長頸鹿慢慢地吃著嫩葉，每一口都像是一幅自然的畫作。我們靜靜觀察著，心中充滿著喜悅和平靜。這一幕彷彿是一個夢境，我們置身於童話世界之中，與大自然共舞。這是一個令人難忘的時刻，會永遠記得這片草原上的和諧與寧靜，以及與長頸鹿難忘的相遇。"""
"設計概念2" = """
Its neck stretches high, reaching for the leaves,
Nourishing its body, fulfilling its needs.
In the golden sunlight, it gracefully strides,
A gentle giant, where beauty and strength collide."""

["價格"]
"定價" = 7200
"假日" = 4500
"旺日" = 4000
"平日" = 3600
