["活動"]
"顯示" = "是"               # 是/否
"開始日期" = 2023-05-01     # 一定要填日期
"結束日期" = 2023-05-14     # 一定要填日期
"名稱" = "母親節感恩分享活動 - 抽獎免費住一晚"
"簡述" = "人生旅程中，陪伴著我們最要的角色莫過於媽媽。在這特別的日子裡，邀請大家一同感念母親的養育之恩，分享抽祝福，願每一位媽媽都永遠快樂 ❤️✨"
"說明" = """
#參加方式:即日起至2023/05/14前完成以下兩個
步驟即可抽獎
1.公開分享按此文章+Ta3好友+留言：一起來參加母親節快樂感恩分享抽❤️
2.到AuraVilla-悠悅光按讚
#獎品說明:平日週一至週四,雙人房住宿券
#免費住宿一晚(房型依當日現場為主,不可指定,依當日現場為主)抽一名幸運兒，住宿2023/06/30前使用完畢。
#得獎公佈:於此篇文章留言區於2023/05/16公佈得獎名單!
悠悅光AuraVilla保留最終解釋及活動更改權利。
請按追蹤搶先看[AuraVilla悠悅光]不漏接開獎通知!"""
