["活動"]
"顯示" = "是"               # 是/否
"開始日期" = 2023-05-10     # 一定要填日期
"結束日期" = 2023-05-31     # 一定要填日期
"名稱" = "這就是我的夢 想 豪 宅 !!! 結合質感渡假與親子童趣風格"
"簡述" = "Aura Villa - 悠悅光，擁有時尚純白的建築外觀，後頭竟然藏有一大片寬廣庭院! "
"說明" = """
＼賽車+大戲水池+大沙坑+盪鞦韆+溜滑梯房玩到翻／
同時滿足大人及小人兒的喜好🥰
🈶 超放電驚喜佈置房型：
房型以獅子🦁️、北極熊🐻‍❄️、斑馬🦓、犀牛🦏等可愛動物設計，在房內精心打造✅溜滑梯✅攀爬牆及✅小木屋等質感設施！
戶外還有✅兒童戲水池、✅沙坑、✅小型賽車場、✅盪鞦韆、✅搖搖椅等可讓小人兒玩得超過癮🤩~ 還可以在✅大草坪上奔跑吹泡泡都不是問題，且周圍碧草如茵靠近梅花湖，讓心情超級放鬆 💆！
媽咪可當網美~~房間跟戶外泳池都超好拍喔!
🈶 新鮮早餐及美味下午茶：
入住即刻便能享用😋美味下午茶(含蛋糕、布丁、熱咖啡等不定期更換)，大廳還擺放可免費取用的米果餅乾及冰箱冷飲🤩；早上還有民宿管家 💪現做營養西式早餐，新鮮美味！
🈶 騎鐵馬漫遊梅花湖畔：
距📍羅東夜市約20分鐘車程，離其他知名景點也不遠。而離📍梅花湖走路只要7分鐘，可跟管家借腳踏車前往，或是到梅花湖畔租電動造型車環湖。
☑小提醒: 假日一房難求，建議提前3個月預訂唷~"""
