["基本"]
"名稱" = "斑馬"
"代號" = "T1"
"房型" = "四人房"
"特別設備" = "小木屋"

["簡要"]
"設計概念" = "以斑馬獨特的條紋圖案為靈感，打造仿如小木屋般的自然風格房型設計。"
"床型" = "雙人床 x 2"

["詳細"]
"標題" = "✨✨ 與各種迷人的動物互動，感受與自然的真摯連結 ✨✨"
"設計概念1" = """斑馬的獨特條紋圖案常常啟發著人們的創造力。以斑馬的條紋圖案為靈感，我們打造出仿如小木屋般的自然風格房型設計。這樣的風格能夠帶來自然、舒適和溫暖的氛圍，讓旅客能夠在其中放鬆身心，享受寧靜和平和的氛圍。
以斑馬條紋圖案為靈感的房型設計充滿了原始而有機的感覺。我們運用木質材料和天然色調來營造房間的氛圍。這樣的設計元素與斑馬的自然環境相呼應，讓居住其中的人們能夠感受到大自然的美好和平衡。
小木屋營造出一種與自然和諧共處的氛圍。透過大窗戶讓自然光線充分進入房間。讓居住者感受到大自然的活力和清新，同時為他們提供一個舒適、放鬆的住宿環境。"""
"設計概念2" = """
In the golden savannah, where the sunsets gleam,
Roams a creature majestic, like a beautiful dream.
With stripes so bold, black and white they display,
The noble zebra gallops, free to roam and play."""

["價格"]
"定價" = 9800
"假日" = 6400
"旺日" = 5900
"平日" = 5200
