["基本"]
"名稱" = "意識流主義"
"代號" = "B3"
"房型" = "雙人房"

["簡要"]
"設計概念" = "意識流主義通過流暢的、不受限制的思想和感官印象的自由流動，呈現人類意識和潛意識的複雜性和深度。"

["詳細"]
"標題" = "✨✨ 時尚家具和當代美學相融合，讓您沉浸於獨特的現代風格 ✨✨"
"設計概念1" = """意識流主義宣言 ~ Stream of Consciousness
意識流主義是20世紀初期興起的一種文學風格，其主要特徵是以模擬人物內心意識流動的方式來組織文學作品。這種文學形式旨在深入描繪人物的思想、情感和感知過程，並將其以一種自由流動的方式呈現出來。
意識流文學關注個體內心的思維和感受，通過模擬人物的意識流動，試圖展示出內心複雜而無法捉摸的運作方式。這種寫作風格常常包含了無意識、夢幻、回憶、語言前意識等多種意識形態的表現形式。作家們運用長篇的內心獨白、自由聯想、碎片化的片段和流動的語言結構來呈現人物的內心世界。
意識流主義的作品常常具有複雜的時間和空間結構。作家們通過使用時間的蒙太奇（montage）手法，將不同時刻的意識片段交錯組織在一起，以呈現人物內心的思緒連貫性和非線性特徵。同樣地，他們也利用空間的蒙太奇，將不同地點的意識場景交錯呈現，以表現出人物內心的情感和感知的多元性。"""
"設計概念2" = """
The voyage of discovery is not in seeking
new landscapes but in having new eyes.
_ Marcel Proust"""

["價格"]
"定價" = 8000
"假日" = 5200
"旺日" = 4600
"平日" = 4000
