["基本"]
"名稱" = "象徵主義"
"代號" = "A1"
"房型" = "四人房"

["簡要"]
"床型" = "雙人床 x 2"
"設計概念" = "象徵主義強調藝術品中的符號、隱喻和意象，以表達抽象概念和情感"

["詳細"]
"標題" = "✨✨ 選擇你的現代主義，感受設計與美學的融合 ✨✨"
"設計概念1" = """象徵主義宣言 ~ Symbolism
象徵主義是19世紀末至20世紀初的一個文學運動，主要在法國興起，並逐漸擴展到歐洲其他地區。象徵主義詩歌和戲劇主張以隱喻、象徵和意象來表達情感和思想，追求詩歌的音樂性和瀰漫的氛圍。
象徵主義文學認為詩歌應該超越表面的字義，而是通過隱喻和象徵來揭示更深層的真理和情感。詩人們注重詞語的模糊性和多義性，以及聲音的韻律和節奏。他們選擇那些能夠產生聲音共鳴和意義共鳴的詞語，以營造一種流動的、朦朧的和清靈的詩意氛圍。
在象徵主義詩歌中，色彩和形象的運用非常重要。詩人們常常使用色彩暈染的方式來描繪情感和意念，通過色彩的聯想和連結，營造出詩歌的獨特氛圍和情感共鳴。他們追求意象的豐富性和多樣性，以及意象之間的意義連結和象徵性的隱喻。"""
"設計概念2" = """
Your soul is like a painter's landscape
where charming masks in shepherd
mummeries are playing lutes and dancing
with an air of being sad in their fantastic
guise.
_Paul Verlaine"""

["價格"]
"定價" = 10900
"假日" = 7500
"旺日" = 6500
"平日" = 5500
