["標題"]
標題1 = "新美館"
子標題1 = "全新推出，敬請期待。"
標題2 = "與您一起共享這片美麗"
子標題2 = "新美館提供多種精彩的設施和活動，讓您的渡假時光豐富多變。"

["活動"]
"名稱" = "母親節感恩分享活動 - 抽獎免費住一晚"
簡述 = "人生旅程中，陪伴著我們最要的角色莫過於媽媽。在這特別的日子裡，邀請大家一同感念母親的養育之恩，分享抽祝福，願每一位媽媽都永遠快樂 ❤️✨"
