["基本"]
"名稱" = "犀牛"
"代號" = "T3"
"房型" = "雙人房"
"特別設備" = "攀爬牆"

["簡要"]
"設計概念" = "以犀牛為設計概念，加入攀爬牆元素，打造充滿挑戰與樂趣的房型"

["詳細"]
"設計概念1" = """未來主義宣言。
二十世紀初，受到工業革命影響，電力與機械的使用徹底衝擊人們對於時間，速度和光線的感受。代表了一個時代的轉變與思維方式的變革。這篇宣言的出現標誌著藝術的現代主義運動開始了，這也是一個重要的文化和社會現象。未來主義者不僅關注藝術和文學，更關注科學和技術，他們希望通過藝術來反映這種新生活方式的創造。
義大利詩人馬里內諦 (Filippo Tommaso Marinetti) 於 1909 年發表<em><strong>未來主義者宣言</strong></em>，揚棄傳統藝術即陳舊思想，主張藝術家應全力追求速度，歌頌科技與力量。除了繪畫、雕塑和音樂等傳統藝術形式，未來主義藝術家們的創作興趣還延伸到了其他領域，例如詩歌、戲劇和烹飪等。他們強調速度、科技和暴力等元素的重要性，視汽車、飛機和工業化的城市等為人類技術進步征服自然的象徵。"""
"設計概念2" = """
The poet must spend himself with ardor,
splendor, and generosity, to swell the
enthusiastic fervor of the primordial
elements.
_Filippo Tommaso Marinett"""