["基本"]
"名稱" = "麋鹿"
"代號" = "T2"
"房型" = "雙人房"
"特別設備" = "溜滑梯"

["簡要"]
"設計概念" = "以麋鹿生活在森林中的天性為設計概念，加入溜滑梯元素，打造自然舒適且充滿遊樂性的房型。"

["詳細"]
"標題" = "✨✨ 讓身心靈全面放鬆，創造難忘的回憶 ✨✨"
"設計概念1" = """以麋鹿生活在森林中的天性為設計概念，我們打造了一個自然舒適且充滿遊樂性的房型，並加入溜滑梯元素。麋鹿是森林中的優雅生物，擁有輕盈的步伐和敏銳的感知力。透過在房間中融入麋鹿的元素，例如森林風格的裝飾、掛飾或立體造型，營造出自然舒適的氛圍，讓旅客感受到森林中的寧靜和和諧。
我們在房間中安置一個特別設計的溜滑梯，仿佛是麋鹿的棲息地中的一部分。這個溜滑梯設置在房間的一角，並融入自然元素，增加了與自然的聯繫感。小朋友可以在房間中盡情遊玩溜滑梯，仿佛成為森林中的一員，與麋鹿一同展開冒險。
這樣的房型設計不僅帶來自然舒適的感覺，還增添了房間的遊樂性。住宿者在祥和中融入自然的氛圍。這是一個舒適、自然且充滿遊樂性的空間，能夠在家中感受到與自然共舞的愉悅。"""
"設計概念2" = """
In the forest's gentle embrace,
A graceful creature roams with grace,
The majestic deer with antlers wide,
In nature's beauty, it takes great pride."""

["價格"]
"定價" = 8200
"假日" = 4900
"旺日" = 4300
"平日" = 4000
