["基本"]
"名稱" = "犀牛"
"代號" = "T3"
"房型" = "雙人房"
"特別設備" = "攀爬牆"

["簡要"]
"設計概念" = "以犀牛為設計概念，加入攀爬牆元素，打造充滿挑戰與樂趣的房型。"

["詳細"]
"標題" = "✨✨ 入住我們的動物主題民宿，體驗與大自然的和諧與平靜 ✨✨"
"設計概念1" = """以犀牛為設計概念，我們打造一個充滿挑戰與樂趣的房型，並加入攀爬牆元素。犀牛是大自然中堅強且強壯的動物，以其厚重的身軀和堅固的角聞名。透過在房間中融入犀牛的圖案或立體造型，營造出強烈的動感和挑戰性的氛圍，讓旅客能夠在室內感受到犀牛的力量和勇氣。
我們在房間中建造一個特別設計的攀爬牆，仿佛是犀牛的領地中的一部分。這個攀爬牆可以設置在房間的一側，並具有不同程度的難度，讓小朋友能夠挑戰自己的力量和靈活性。透過攀爬，運動員仿佛成為一名勇敢的冒險家，體驗到犀牛般的堅毅和勇氣。
這房型不僅帶來挑戰性和樂趣，還為房間增添了一份獨特的魅力，體驗到犀牛般的堅毅和勇氣，並享受攀爬的樂趣。"""
"設計概念2" = """
Oh, noble rhinoceros, with armor adorned,
A symbol of strength, in the wild untamed.
Your massive frame, like an ancient tree,
Embodies resilience, for all to see."""

["價格"]
"定價" = 6800
"假日" = 4300
"旺日" = 3900
"平日" = 3500
